version: '3.8'
services:

  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    ports:
      - 25565:25565
    volumes:
      - /path/to/folder/on/server:/data
    environment:
      - EULA=TRUE
    restart: unless-stopped

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - /path/to/folder/on/server/data:/data
      - /path/to/folder/on/server/letsencrypt:/etc/letsencrypt
    environment:
      -  DB_SQLITE_FILE = /data/database.sqlite
      -  DISABLE_IPV6 = true
    restart: unless-stopped