version: '3.8'
services:

  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    ports:
      - 25565:25565
    volumes:
      - /raid0/docker/minecraft:/data
    environment:
      - EULA=TRUE
      - MOTD="Gurras Minecraftserver"
      - MAX_PLAYERS=50
      - MAX_WORLD_SIZE=10000
      - ALLOW_NETHER=true
      - PVP=false
      - ALLOW_FLIGHT=TRUE
      - SERVER_NAME=Gurra
      # Java Settings
      - MEMORY=2G # Denna är väll den enda viktiga, 2gig borde räcka för vanligt omoddat minecraft
      - INIT_MEMORY=1G
      - MAX_MEMORY=4G
    restart: unless-stopped

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - /raid0/docker/npm/data:/data
      - /raid0/docker/npm/letsencrypt:/etc/letsencrypt
    environment:
      -  DB_SQLITE_FILE=/data/database.sqlite
      -  DISABLE_IPV6=true
    restart: unless-stopped